---
title: "Power or sample size" 
author: 
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    source_code: embed
runtime: shiny
---
Binary endpoint
===

```{r global, include=FALSE}

  rm(list=ls())
  set.seed(6453)
    # for neg binomial analysis and correlated data generation
  library(ggplot2)
  
   
 # library(gridExtra)
  library(tidyverse)
  library(plotly)
  library(Hmisc)
 # lwd.=3             # used when plotting
  
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # function to format decimals
  # https://stackoverflow.com/questions/3245862/format-numbers-to-significant-figures-nicely-in-r
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  formatz <- function(x){
    
    if (!is.na(x)  ) {
      
      formatC(signif(x,digits=5), digits=5,format="fg", flag="#",big.mark=",")
      
    }
    
  }
  
  formatz0 <- function(x){
    sprintf(x, fmt = '%s')  
  }
  formatz1 <- function(x){
    sprintf(x, fmt = '%#.1f')  
  }
  formatz2 <- function(x){
    sprintf(x, fmt = '%#.2f')  
  }
  formatz00 <- function(x){
    round(x,0) 
  }
  formatz3 <- function(x){
    sprintf(x, fmt = '%#.3f')  
  }
  formatz4 <- function(x){
    sprintf(x, fmt = '%#.4f')  
  }
  
 
 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# start of app
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Column {.sidebar}
-----------------------------------------------------------------------

**Enter parameters of interest separated by a comma. Up to six scenarios at once can be evaluated**

```{r tab1}

  
          splitLayout(
          textInput("alpha", div(h5(tags$span(style="color:blue", "alpha (type I error)"))), 
          value= "0.05, 0.05,0.05, 0.05,0.05, 0.05"), 
                                       )
  
          splitLayout(
          textInput("p1",    div(h5(tags$span(style="color:blue", "hypothesised proportion p1"))),    
          value= "0.2,0.2,0.2,0.2,0.2,0.2"),)
           
          splitLayout(
          textInput("p2",    div(h5(tags$span(style="color:blue", "hypothesised proportion p2"))),    
          value= "0.1,0.1,0.1,0.25,0.3,0.4"),)
                                         
          splitLayout(
          textInput("ro",    div(h5(tags$span(style="color:blue", "ratio for unequal randomisation"))),   
          value= "1,2,3,1,2,3"),)                                
                                        
          sliderInput('x_range', 'Plot x-range', value = c(0,800),
                  min = 0, max = 5000,step=100,ticks=F)
          
          sliderInput('y_range', 'Plot y-range', value = c(0,1),
                  min = 0, max = 1,step=.05,ticks=F)

   
          br()
   
       
xx <- reactive({
  
    A <-   (as.numeric(unlist(strsplit(input$alpha,","))))    
    
    A1 <- A[1]
    A2 <- A[2]
    A3 <- A[3]
    A4 <- A[4]
    A5 <- A[5]
    A6 <- A[6]
  
    Az<-   (as.numeric(unlist(strsplit(input$p1,","))))    
    
    P1 <- Az[1]
    P2 <- Az[2]
    P3 <- Az[3]
    P4 <- Az[4]
    P5 <- Az[5]
    P6 <- Az[6] 

    Aa<-   (as.numeric(unlist(strsplit(input$p2,","))))    
    
    P1B <- Aa[1]
    P2B <- Aa[2]
    P3B <- Aa[3]
    P4B <- Aa[4]
    P5B <- Aa[5]
    P6B <- Aa[6] 


    Ab<-   (as.numeric(unlist(strsplit(input$ro,","))))    
    
    R1 <- Ab[1]
    R2 <- Ab[2]
    R3 <- Ab[3]
    R4 <- Ab[4]
    R5 <- Ab[5]
    R6 <- Ab[6] 
               
#     ## Function to calculate n1 and n2 based on k and S
# calculate_n1_n2 <- function(k, S) {
#     n2 <- S / (k + 1)
#     n1 <- k * n2
#     return(c(n1 = n1, n2 = n2))
# }
# 
# # Example usage with k = 3 and S = 200
# k <- 1
# S <- 200
# 
# A1 <- A2 <- A3 <- A4 <- A5 <- A6 <- .05
# #
#  P1 =2; P2=.7 ; P3 <- P4 <- P5 <- P6 <- .2
# #
#  P1B <- P2B <- P3B <- P4B <- P5B <- P6B <- .4
# #
#  R1 <- R2 <- R3 <- R4 <- R5 <- R6 <- 1
# 
#  sample_sizes <- seq(10, 100, by = 10)
  # 
    
   sample_sizes <- seq(10, input$x_range[2], by = 10)
  # 
   #---------------------------------------------------------------
 #  trying to get n1 n2 ...etc and power to list, inefficient as I do the calc again!
    s = length(sample_sizes)
 
    res = matrix(NA, 6*s, 9)
   
    x <- s*6
      
    ind <- 1

    #-----------------------------------------------------------------------  
      
    for (j in 1:s) {
   
        for(i in 1:6) {
   
                   res[ind,1] <- i     # group 
                   res[ind,2] <- sample_sizes[j]  # total sample size
            n1 <-  res[ind,3] <- sample_sizes[j]/((eval(parse(text = paste0("R",(i)))))+1)  # n1
            n2 <-  res[ind,4] <- eval(parse(text = paste0("R",(i))))* sample_sizes[j]/
                                (eval(parse(text = paste0("R",(i))))+1)    # n2
            r <-   res[ind,5] <-(eval(parse(text = paste0("R",(i)))))      # ratio
            p1 <-  res[ind,6] <-(eval(parse(text = paste0("P",(i)))))      # p1
            p2 <-  res[ind,7] <-(eval(parse(text = paste0("P",(i),"B"))))  # p2
            a1 <-  res[ind,8] <-(eval(parse(text = paste0("A",(i)))))      # alpha
    
                  # do the calculation, feed in 
                   res[ind,9]  <- bpower(n1 = n1, 
                                         n2 =n2, p1 = p1, p2 =  p2, alpha = a1)
      
   ind=ind+1
   
    }
  }
      
  #-----------------------------------------------------------------------    
      res<- data.frame(res)
      names(res) <- c("Index", "N","n1","n2","ratio", "P1","P2", "alpha","power")
      res <- plyr::arrange(res,Index ,N)
      res$n1 <- round(res$n1,2)
      res$n2 <- round(res$n2,2)
      res$power <- round(res$power,4)
  #-------------------------------------------------------
 
  # code to help with legend
 
      x <- res
    
      x$phrase <- with(x, paste("p1=",x$P1,"p2=",x$P2,"\nalpha=",x$alpha, "ratio=",x$ratio))
    
      x$r <- ifelse(x$ratio !=1,"Unequal","Equal")  
    
      x$variable <- rep(1:6, each=length(sample_sizes)) 
    
      x$variable <- x$Index
        
      x$variable <- factor(x$variable)
    
      x$tag <-  paste(as.character(x$variable),as.character(x$phrase))

  #-----------------------------------------------------------------------
    return(list(  
      
      x=x , res=res
      
     ))    

})

 
```

$\alpha$ type I assertion error $\beta$ not required


 

<!-- Column {data-width=600, height=600} -->
<!-- ----------------------------------------------------------------------- -->
<!-- ### Chart 1 -->

 
## Column {.tabset .tabset-fade}

### Chart 1

```{r tab1 plot1}

renderPlot({
  
  p =      xx()$x
  
  #-----------------------------------------------------------------------
  skips <- ifelse(input$x_range[2] <= 1000, 50,
                ifelse(input$x_range[2] > 1000 & input$x_range[2] < 3000 ,200
                       ,  500))
   
  #https://stackoverflow.com/questions/18515588/dynamic-legend-labels-in-ggplot2
  legendlabels <- data.frame(
                    'stadtland'= unique(p$tag),
                    stringsAsFactors=FALSE)

  #-----------------------------------------------------------------------
  
  all <-ggplot(p, aes(x = N, y = power, linetype=r,
                    group=variable,
                    colour = variable)) +
  geom_line() +
    
    scale_color_manual( labels=legendlabels[['stadtland']], # c("a","b","c","d","e","f"),
                        values = c("red", "green", "blue", "purple","black","orange")) +

  scale_y_continuous(breaks = seq(input$y_range[1], input$y_range[2], by = 0.1),  
                     limits = c(input$y_range[1], input$y_range[2])) +
  scale_x_continuous(breaks = seq(input$x_range[1],input$x_range[2],skips), limits = c(input$x_range[1],input$x_range[2])) +
  theme_bw() +
  theme( 
    plot.title=element_text(size = 19, face="bold"), plot.margin = unit(c(5.5,12,5.5,5.5), "pt"),
     
    legend.text=element_text(size=13),
    legend.title=element_text(size=13.5, face="bold"),
    legend.position="right",
   #https://ggplot2.tidyverse.org/articles/faq-customising.html gaps in legend
    legend.key.size = unit(1.3, "cm"),
    legend.key = element_rect(color = NA, fill = NA),
    
    axis.text.x  = element_text(size=12),
    axis.text.y  = element_text(size=12),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),
   
    plot.caption=element_text(hjust = 0, size = 12),
    strip.text.x = element_text(size = 16, colour = "black", angle = 0),
    axis.title.y = element_text(size = rel(2), angle = 90),
    axis.title.x = element_text(size = rel(2), angle = 0 ),
    
    strip.background = element_rect(colour = "black", fill = "white"),
    panel.background = element_rect(fill = 'white', colour = 'white'),
    plot.background = element_rect(fill = 'white', colour = 'white')
  ) +
  
  
  labs(y="Power", x = 'Total Sample Size', color = "Population probabilities", linetype="Ratio" )+
  labs(caption = paste("- Ratio, see legend, >1 pertains to when p1 is the larger sample size and <1 when p1 is the smaller sample size.\n- Where the ratio of sample sizes n1/n2=x in one case and n2/n1=x in another (where x is a constant) the power of the test differs between these scenarios.\n- Uses method of Fleiss, Tytun, and Ury (but without the continuity correction) to estimate the power (or the sample size to achieve a given power) of a two-sided test for the difference in two proportions. \n- Fleiss JL, Tytun A, Ury HK (1980): A simple approximation for calculating sample sizes for comparing independent proportions. Biometrics 36:343–6.\n" )) +
  ggtitle(paste0("Power (or sample size) for difference in two proportions for evaluation of treatment effect.") ) 

#https://stackoverflow.com/questions/15059093/ggplot2-adjust-the-symbol-size-in-legends
all <- all + guides(color = guide_legend(override.aes = list(linewidth = 3 )))

print(all)
  #-----------------------------------------------------------------------
#ggplotly(all)
 })
 
```

### Listing

```{r listing}



``` 

```{r listing2}


 DT::renderDataTable({

    w1 <-  xx()$res
    
    DT::datatable(w1, rownames=FALSE,
                  plugins = 'natural',
                  options = list(
                    columnDefs = list(list(type = 'natural', targets = c(4,5)))
                  ))
})
  
 
``` 


Survival
====
```{r, survival}

```

Column {.sidebar}
-----------------------------------------------------------------------

**Enter parameters of interest separated by a comma. Up to six scenarios at once can be evaluated**

```{r surv1}

  
          splitLayout(
          textInput("alphas", div(h5(tags$span(style="color:blue", "alpha (type I error)"))), 
          value= "0.05, 0.05,0.05, 0.05,0.05, 0.05"), 
                                       )
  
          splitLayout(
          textInput("hrs",    div(h5(tags$span(style="color:blue", "hazard ratio"))),    
          value= "2,1.5,0.9,2,1.5,0.9"),)
           
          splitLayout(
          textInput("sidess",    div(h5(tags$span(style="color:blue", "one or two sided"))),    
          value= "2,2,2,1,1,1"),)
                                         
          splitLayout(
          textInput("ros",    div(h5(tags$span(style="color:blue", "ratio for unequal randomisation"))),   
          value= "1,2,3,1,2,3"),)                                
                                        
          sliderInput('x_ranges', 'Plot x-range', value = c(0,400),
                  min = 0, max = 5000,step=100,ticks=F)
          
          sliderInput('y_ranges', 'Plot y-range', value = c(0,1),
                  min = 0, max = 1,step=.05,ticks=F)

   
          br()
          
                
s1 <- reactive({
  
# adapted from gsDesign::nEvents
  

           fsupower <- function (hr = NA, alpha = 0.025,
                      beta = 0.1, ratio = 1, sided = 1, hr0 = 1, n = 0 )
{
   
    if (sided != 1 && sided != 2) sided=NA
    #    stop("sided must be 1 or 2")
             
  
        c <- sqrt(ratio)/(1 + ratio)
       
        # new code so graph is shown if a hr is missing form the 6 hrs allowed
        if(is.na(hr)| is.na(sided)) { 
          hr=NA; pwr=NA; delta=0; se=0; sided=NA
          
        } else {
        
        
        # my fix for the hr > 1 behaviour
        if(hr>1) {
        delta <- -c * -(log(hr) - log(hr0))
        } else {
        delta <- -c * (log(hr) - log(hr0))
        }
        

        pwr <- stats::pnorm(-(stats::qnorm(1 - alpha/sided) - sqrt(n) * delta))
        }
     
        
            pwr <- data.frame(cbind(hr = hr, n = n, alpha = alpha, 
                sided = sided, beta = 1 - pwr, Power = pwr, delta = delta, 
                ratio = ratio, hr0 = hr0, se = sqrt(1/n)/c))
        
        return(pwr)
 
}
    # fsupower(hr = 10/3, n = c(10,20),   alpha=0.05, sided =2, ratio=1)
    # fsupower(hr = .3, n = c(10,20),   alpha=0.05, sided =2, ratio=1)
    # 
    # gsDesign::nEvents(hr = .5, n = 50, tbl = TRUE , alpha=0.05, sided =1,  ratio =c(2,.5))
    # gsDesign::nEvents(hr = 2, n = 50, tbl = TRUE , alpha=0.05, sided =1,  ratio =c(2,.5))
    
    A <-   (as.numeric(unlist(strsplit(input$alphas,","))))    
    
    A1 <- A[1]
    A2 <- A[2]
    A3 <- A[3]
    A4 <- A[4]
    A5 <- A[5]
    A6 <- A[6]
  
    realHR <- Az<-   (as.numeric(unlist(strsplit(input$hrs,","))))    
    
    P1 <- Az[1]
    P2 <- Az[2]
    P3 <- Az[3]
    P4 <- Az[4]
    P5 <- Az[5]
    P6 <- Az[6] 

    Aa<-   (as.numeric(unlist(strsplit(input$sidess,","))))    
    
    P1B <- Aa[1]
    P2B <- Aa[2]
    P3B <- Aa[3]
    P4B <- Aa[4]
    P5B <- Aa[5]
    P6B <- Aa[6] 


    Ab<-   (as.numeric(unlist(strsplit(input$ros,","))))    
    
    R1 <- Ab[1]
    R2 <- Ab[2]
    R3 <- Ab[3]
    R4 <- Ab[4]
    R5 <- Ab[5]
    R6 <- Ab[6] 
               
  sample_sizes <- seq(10, input$x_ranges[2], by = 10)
   
 
# List of objects
# objects_list <- list(P1, P2, P3, P4, P5, P6)
# 
# object_names <- c("P1", "P2", "P3", "P4", "P5", "P6")
# 
# note <-  objects_list > 1
# 
# # Function to replace the value with its reciprocal if less than 1
# replace_with_reciprocal <- function(x) {
#   if (x > 1) {
#     x <- 1 / x
#   }
#   return(x)
# } 
# 
# for (object_name in object_names) {
#   assign(object_name, replace_with_reciprocal(get(object_name)))
# } 


   
    # divide by 2 for totl
# A <- gsDesign::nEvents(hr = P1, n = sample_sizes, tbl = TRUE , alpha=A1, sided =P1B, ratio=R1)
# 
# 
# B <- gsDesign::nEvents(hr = P2, n =sample_sizes, tbl = TRUE , alpha=A2, sided =P2B, ratio=R2)
#  
# C <- gsDesign::nEvents(hr = P3, n =sample_sizes, tbl = TRUE , alpha=A3, sided =P3B, ratio =R3)
# D <- gsDesign::nEvents(hr = P4, n =sample_sizes, tbl = TRUE , alpha=A4, sided =P4B, ratio =R4)
#  
# E <- gsDesign::nEvents(hr = P5, n =sample_sizes, tbl = TRUE , alpha=A5, sided =P5B, ratio =R5)
# F <- gsDesign::nEvents(hr = P6, n = sample_sizes, tbl = TRUE , alpha=A6, sided =P6B,  ratio =R6)
  
# fsupower(hr = 10/3, n = c(10,20),   alpha=0.05, sided =2, ratio=1)

A <- fsupower(hr = P1, n = sample_sizes,   alpha=A1, sided =P1B, ratio=R1)
B <- fsupower(hr = P2, n =sample_sizes,    alpha=A2, sided =P2B, ratio=R2)
C <- fsupower(hr = P3, n =sample_sizes,   alpha=A3, sided =P3B, ratio =R3)
D <- fsupower(hr = P4, n =sample_sizes,   alpha=A4, sided =P4B, ratio =R4)
E <- fsupower(hr = P5, n =sample_sizes,   alpha=A5, sided =P5B, ratio =R5)
F <- fsupower(hr = P6, n = sample_sizes,  alpha=A6, sided =P6B,  ratio =R6)



   # gsDesign::nEvents(hr = .5, n = 50, tbl = TRUE , alpha=0.05, sided =1,  ratio =c(2,.5))
   #  
   # gsDesign::nEvents(hr = .5, n = 50, tbl = TRUE , alpha=0.05, sided =1,  ratio =c(3,1/3))
   # 
   # cpower(tref, n, mc, r, accrual, tmin, noncomp.c=0, noncomp.i=0, 
   #     alpha=0.05, nc, ni, pr=TRUE)
   # 
  #---------------------------------------------------------------
  
  x <- rbind(A,B,C,D, E, F)
  
  x$n2 <- x$n / (x$ratio + 1)
  x$n1 <- x$ratio * x$n2
  
  # real HR goes back as we flipped those >1 (gdesign function is weird) and it would be confusing on legend
  # x$hr <- rep(realHR, each=length(sample_sizes)) 
  
  x$hr <- factor(x$hr)
  
  
  
  
      res <- x
      res<- data.frame(res)
      res$n1 <- round(res$n1,2)
      res$n2 <- round(res$n2,2)
      res$Power <- round(res$Power,4)
  # #-------------------------------------------------------
  # 
  # code to help with legend

      x <- res

      x$phrase <- with(x, paste("HR=",x$hr, "ratio=",x$ratio, "\nalpha=",x$alpha, "sided=",x$sided) )

      # x$actual_ratio <- x$ratio
      
      x$ratio <- ifelse(x$ratio !=1,"Unequal","Equal")

      x$variable <- rep(1:6, each=length(sample_sizes))

     # x$variable <- x$Index

      x$variable <- factor(x$variable)

      x$tag <-  paste(as.character(x$variable),as.character(x$phrase))

       x$ratio <- factor(x$ratio)
  #-----------------------------------------------------------------------
    return(list(  
      
      xy=x 
      
     ))    

})

```
$\alpha$ type I assertion error $\beta$ not required
 
<!-- ### Chart 1 -->

 
## Column {.tabset .tabset-fade}

### Chart 2

```{r surv plot1, eval=TRUE}


renderPlot({
  
 p =      s1()$xy
  
  #-----------------------------------------------------------------------
  skips <- ifelse(input$x_ranges[2] <= 1000, 50,
           ifelse(input$x_ranges[2] > 1000 & input$x_ranges[2] < 3000 ,200
                       ,  500))

  #https://stackoverflow.com/questions/18515588/dynamic-legend-labels-in-ggplot2
  legendlabels <- data.frame(
                    'stadtland'= unique(p$tag),
                    stringsAsFactors=FALSE)

   p <- p[,c( "n",  "n2", "n1" , "hr", "alpha", "sided",   "Power",   "ratio", 
  "variable")]
  #-----------------------------------------------------------------------
 
  all <-ggplot(p, aes(x = n, y = Power, 
                    linetype=ratio,
                    #group = interaction(ratio, hr),
                    
                    group=variable,
                    colour = variable)) + # # had hr here initally mis match with legend
  geom_line() +

    scale_color_manual( labels=legendlabels[['stadtland']], # c("a","b","c","d","e","f"),
                        values = c("red", "green", "blue", "purple","black","orange")) +

    # scale_color_manual( labels=unique(p$tag), # c("a","b","c","d","e","f"),
    #                     values = c("red", "green", "blue", "purple","black","orange")) +

  scale_y_continuous(breaks = seq(input$y_ranges[1], input$y_ranges[2], by = 0.1),
                       limits = c(input$y_ranges[1], input$y_ranges[2])) +
  scale_x_continuous(breaks = seq(input$x_ranges[1], input$x_ranges[2],skips), limits =                                    c(input$x_ranges[1], input$x_ranges[2])) +
  theme_bw() +
  theme(
    plot.title=element_text(size = 19, face="bold"), plot.margin = unit(c(5.5,12,5.5,5.5), "pt"),

    legend.text=element_text(size=13),
    legend.title=element_text(size=13.5, face="bold"),
    legend.position="right",
   #https://ggplot2.tidyverse.org/articles/faq-customising.html gaps in legend
    legend.key.size = unit(1.3, "cm"),
    legend.key = element_rect(color = NA, fill = NA),

    axis.text.x  = element_text(size=12),
    axis.text.y  = element_text(size=12),
    axis.line.x = element_line(color="black"),
    axis.line.y = element_line(color="black"),

    plot.caption=element_text(hjust = 0, size = 12),
    strip.text.x = element_text(size = 16, colour = "black", angle = 0),
    axis.title.y = element_text(size = rel(2), angle = 90),
    axis.title.x = element_text(size = rel(2), angle = 0 ),

    strip.background = element_rect(colour = "black", fill = "white"),
    panel.background = element_rect(fill = 'white', colour = 'white'),
    plot.background = element_rect(fill = 'white', colour = 'white')
  ) +


  #-----------------------------------------------------------------------



  labs(y="Power", x = 'Total Number of events', color = "Hazard ratio", linetype="Ratio" )+
 
  labs(caption = paste("- Alpha the type I assertion probability.  Note, total number of patients requires information on accrual duration and maximum follow up times. If ratio <1 n1 is the smaller group. \n- Uses method of Schoenfeld two-sided test for the ratio of two hazards. Assuming exponential hazards.\n- Schoenfeld DA. Sample-size formula for the proportional-hazards regression model. Biometrics 1983;39:499-503.\n" )) +

  ggtitle(paste0(" Power (or number of events) for hazard ratio assuming exponential hazards)") )


#https://stackoverflow.com/questions/15059093/ggplot2-adjust-the-symbol-size-in-legends
all <- all + guides(color = guide_legend(override.aes = list(linewidth = 3 )))

print(all)
#-----------------------------------------------------------
#ggplotly(all)
 })
 
```

### Listing

```{r listings}



``` 

```{r listings2}


 DT::renderDataTable({

    p <-  s1()$xy
    
       p <- p[,c( "n",  "n2", "n1" , "hr", "alpha", "sided",   "Power",    "ratio" )]
    DT::datatable(p, rownames=FALSE,
                  plugins = 'natural',
                  options = list(
                    columnDefs = list(list(type = 'natural', targets = c(4,5)))
                  ))
})
  
 

``` 
<!-- ### Chart 2 -->

<!-- ```{r, tab1 plot2} -->


<!-- ```   -->

References
====
```{r, refs}
 
    tags$a(href = "https://stats.stackexchange.com/questions/71194/fitting-a-poisson-distribution-with-lme4-and-nlme", target="_blank",
           tags$span(style="color:blue", "[1] Poisson with lme4 and nlme"),) 
    div(p(" "))
    tags$a(href = "https://stats.stackexchange.com/questions/27869/fitting-a-poisson-glm-mixed-model-with-a-random-slope-and-intercept",target="_blank",
           tags$span(style="color:blue", "[2] Mixed model Poisson"),)
    div(p(" "))
    tags$a(href = "https://stackoverflow.com/questions/6044800/adding-greek-character-to-axis-title", target="_blank",
           tags$span(style="color:blue", "[3] Adding Greek characters - shiny"),)
    div(p(" "))
    tags$a(href = "https://stackoverflow.com/questions/52225348/shiny-flexdashboard-reference-object-in-new-tabset#52225733", target="_blank",
           tags$span(style="color:blue", "[4] Reference object in new tab - shiny"),)  
    div(p(" "))
    tags$a(href = "https://journals.sagepub.com/doi/pdf/10.1177/1536867X1201200202", target="_blank",
           tags$span(style="color:blue", "[5] What hypotheses do “nonparametric” two-group tests actually test?"),) 
    div(p(" "))
    tags$a(href = "https://www.google.co.uk/books/edition/Discrete_Data_Analysis_with_R/danODwAAQBAJ?hl=en",target="_blank",
           tags$span(style="color:blue", "[6] Discrete Data Analysis with R Visualization and Modeling Techniques for Categorical and Count Data"),) 
    div(p(" "))
    tags$a(href = "https://www.galitshmueli.com/system/files/ASMB_901_rev.pdf",target="_blank",
           tags$span(style="color:blue", "[7] On generating multivariate Poisson data in management science applications"),) 
    div(p(" "))
    tags$a(href = "https://thomasward.com/simulating-correlated-data/",target="_blank",
           tags$span(style="color:blue", "[8] Simulating correlated data"),) 
    div(p(" "))
    tags$a(href = "https://www.rdocumentation.org/packages/simstudy/versions/0.3.0", target="_blank", 
           tags$span(style="color:blue", "[9] package simstudy for simulating correlated data, not used but interesting"),) 
    div(p(" "))
    tags$a(href = "https://www.rdocumentation.org/packages/SimCorrMix/versions/0.1.1/topics/SimCorrMix",target="_blank", 
           tags$span(style="color:blue", "[10] package SimCorrMix for simulating correlated data, not used but interesting"),) 
    div(p(" "))
    tags$a(href = "https://www.amazon.com/Negative-Binomial-Regression-Joseph-Hilbe/dp/0521198151",target="_blank", 
           tags$span(style="color:blue", "[11] Negative Binomial Regression 2nd Edition by Joseph M. Hilbe"),) 
    div(p(" "))
    tags$a(href = "https://www.amazon.co.uk/Discrete-Data-Analysis-Visualization-Categorical/dp/149872583X",target="_blank", 
           tags$span(style="color:blue", "[12] Discrete Data Analysis with R: Visualization and Modeling Techniques for Categorical and Count Data, Michael Friendly, David Meyer"),) 
    div(p(" "))
    tags$a(href = "https://bmcmedresmethodol.biomedcentral.com/track/pdf/10.1186/s12874-015-0023-0.pdf",target="_blank",
           tags$span(style="color:blue", "[13] Sample size calculations for skewed distributions - see canned power tab"),) 
    div(p(" "))
      tags$a(href = "https://pubmed.ncbi.nlm.nih.gov/17230434/", target="_blank",
           tags$span(style="color:blue", "[14] Analysis of exacerbation rates in asthma and chronic obstructive pulmonary disease: example from the TRISTAN study - see canned power tab "),) 
    div(p(" "))
    tags$a(href = "https://stats.stackexchange.com/questions/10419/what-is-theta-in-a-negative-binomial-regression-fitted-with-r", target="_blank",
           tags$span(style="color:blue", "[15] J Hilbe explains what is reported by R's negative binomial model output "),) 
    div(p(" "))
     tags$a(href = "https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.5947", target="_blank",
           tags$span(style="color:blue", "[16] H. Zhu and H. Lakkis (2014). Sample size calculation for comparing two negative binomial rates, Statistics in Medicine, 33:376-387"),) 
     div(p(" "))
     tags$a(href = "https://www.ejobrien.com/", target="_blank",
           tags$span(style="color:blue", "[17] Sixty percent of the time it works every time <- more apps here!"),) 
    div(p(" "))
  tags$hr()                        

```